# Generated by Django 4.1.4 on 2022-12-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('D', 'Driving'), ('S', 'Studying'), ('L', 'Leisure')], default='D', max_length=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.music')),
            ],
        ),
    ]
